### ISSUE TITLE
Move `samtools sort` from `bwa-mem2 align` to `stats_markdup`

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/readmapping#13]
### Description of feature

Once the `bwa-mem2` only module is designed. Move `samtools sort` from subworkflows `align_pacbio` and `align_ont` to  subworkflow `convert_stats`. `samtools/sort` will replace `samtools/view` in `convert_stats` subworkflow.

**Comment by priyanka-surana** [comment]
@muffato 
We need to decide if we want to use `samtools/view` or `samtools/sort` to convert BAM to CRAM. Either way I want to stay consistent. Thank you.

**Comment by muffato** [comment]
I'd say `samtools/sort` only if the file needs sorting, `samtools/view` otherwise
