### ISSUE TITLE
Support PacBio CLR

### ISSUE THREAD

**Issue by muffato** [sanger-tol/readmapping#24]
### Description of feature

The current minimap2 setting for pacbio is `map-hifi` as this is what we are doing now. But in the past, we didn't have HiFi and were using the CLR reads. It looks like the minimap2 setting in that case should be `map-pb`.
We need to be able to support CLR to align the legacy data

**Comment by priyanka-surana** [comment]
Lets say we have a pacbio BAM file, how would we know if it is CLR vs HiFi or is it something the user provides?

**Comment by muffato** [comment]
Technically, it's something we could guess, cf the occurrences of the string `ccs` in the BAM file, incl. as a `PN`:
```
mm49@tol-head2:/lustre/scratch124/tol/projects/darwin/data/insects/Vanessa_atalanta $ samtools view -H genomic_data/ilVanAtal1/pacbio/m64016_190918_162737.ccs.bc1019_BAK8B_OA--bc1019_BAK8B_OA.bam
(...)
@RG     ID:c5c8fe6a/12--12      PL:PACBIO       DS:READTYPE=CCS;BINDINGKIT=101-789-500;SEQUENCINGKIT=101-789-300;BASECALLERVERSION=5.0.0;FRAMERATEHZ=100.000000;BarcodeFile=/lustre/scratch116/vr/projects/vgp/ref/barcodes/Sequel_16_Barcodes_v3.fasta;BarcodeHash=e418d89cefcbef90f3cb0e6455b7e2a3;BarcodeCount=16;BarcodeMode=Symmetric;BarcodeQuality=Score PU:m64016_190918_162737 PM:SEQUEL       BC:ACACACTCTATCAGATT
@PG     ID:ccs-3.4.1    PN:ccs  VN:3.4.1        DS:Generate circular consensus sequences (ccs) from subreads.   CL:ccs 
@PG     ID:lima VN:1.11.0 (commit v1.11.0)      CL:lima -j 8 --split-bam-named --same --peek-guess --ccs m64016_190918_162737.ccs.bam /lustre/scratch116/vr/projects/vgp/ref/barcodes/Sequel_16_Barcodes_v3.fasta lima/m64016_190918_162737.ccs.bam
(...)
```
but I know some people are interested in using alternative CCS-callers such as DeepConsensus, and I don't know what tags these would set. I think it'd be fine to ask the user to provide the information, e.g. by using a separate datatype in the sample-sheet such as `pacbio_clr`, esp. as this won't happen very often (CLR as an end-result is deprecated, in production we'll only be getting CCS data)

**Comment by priyanka-surana** [comment]
This can be executed with a similar approach to the combined Illumina/HiC subworkflow.

**Comment by priyanka-surana** [comment]
What about the directory structure? Current directory structure for `pacbio` is:
```
    └── pacbio
        ├── assembly.pacbio.ilEraDefo1.cram
        ├── assembly.pacbio.ilEraDefo1.cram.crai
        ├── assembly.pacbio.ilEraDefo1.cram.flagstat
        ├── assembly.pacbio.ilEraDefo1.cram.idxstats
        ├── assembly.pacbio.ilEraDefo1.cram.primary_alignments.stats
        └── assembly.pacbio.ilEraDefo1.cram.stats
```

Will the new structure be like this?
```
   └── pacbio-hifi
        ├── assembly.pacbio.ilEraDefo1.cram
        ├── ...
        └── assembly.pacbio.ilEraDefo1.cram.stats
   └── pacbio-clr
        ├── assembly.pacbio.ilEraDefo1.cram
        ├── ...
        └── assembly.pacbio.ilEraDefo1.cram.stats
```

Or like this?
```
   └── pacbio
        ├── assembly.pacbio_hifi.ilEraDefo1.cram
        ├── ...
        ├── assembly.pacbio_hifi.ilEraDefo1.cram.stats
        ├── assembly.pacbio_clr.ilEraDefo1.cram
        ├── ...
        └── assembly.pacbio_clr.ilEraDefo1.cram.stats
```

**Comment by muffato** [comment]
Both should use `pacbio` as name / directory, not `pacbio_hifi`, `pacbio_clr`. The big question is: is there any species with CCS *and* CLR data for the *same* specimen. I hope not

**Comment by priyanka-surana** [comment]
`dImpGla` has both `clr` and `ccs` but for different individuals. Same for `iHemFuc`.
`fSalTru` has both `clr` and `ccs` for the same individual. Same for `fTraTra`.

**Comment by muffato** [comment]
OK. Thanks for digging this. Can I change my mind 😟 ? I now think that CLR and CCS are different enough in terms of library preparation and sequence properties, and we shouldn't mix them.
CCS is the default, so we can name the CCS directory and files `pacbio`. But let's name the CLR files as `pacbio_clr` (and the directory can be named `pacbio` or `pacbio_clr` - I don't think I have an opinion on that)

**Comment by muffato** [comment]
Yes 😄 . Thank you !

**Comment by muffato** [comment]
Do you actually need CLR data for a large genome ?
Regardless, the download of CLR data for fSalTru1 is ongoing, but it's taking a while. It's downloaded 270 GB so far, out of ~900 GB (only two BAM files + indexes)

**Comment by muffato** [comment]
The first file is ready in `/lustre/scratch123/tol/teams/tolit/users/mm49/nextflow/pacbio_clr/fSalTru1/subreads_for_ccs`: `m64016_190129_193902.subreads.bam`. The second one is about half-way through.

Those files are huge because they include the kinetics data. You should see a sharp decrease when transforming those to fastq

**Comment by muffato** [comment]
Second file complete: `m64016_190201_181512.subreads.bam` in the same directory

**Comment by priyanka-surana** [comment]
PacBio CLR testing completed successfully #31.
