### ISSUE TITLE
Filtering and alignments of Hi-C reads

### ISSUE THREAD

**Issue by muffato** [sanger-tol/readmapping#25]
### Description of feature

We need to understand whether the Hi-C reads need to be filtered prior to being aligned, and what filter should be used. The Hi-C pipeline used in production in GRIT involves a locally modified copy of https://github.com/ArimaGenomics/mapping_pipeline which severely filters the reads compared to the official Arima pipeline, or the Hi-C option of BWA MEM2.

Questions to answer:
 - Arima filter or not ? And if yes, which version
 - BWA or BWA-MEM2

**Comment by muffato** [comment]
Don't know if you had the chance to try this. I selected one of the Hi-C files, and here are the`samtools flagstats` reports.

Original file:
```
273148944 + 633894 in total (QC-passed reads + QC-failed reads)
273148944 + 633894 primary
(...)
273148944 + 633894 paired in sequencing
136574472 + 316947 read1
136574472 + 316947 read2
(...)
```

After filtering with `-F0xB00`:
```
273148944 + 0 in total (QC-passed reads + QC-failed reads)
273148944 + 0 primary
(...)
273148944 + 0 paired in sequencing
136574472 + 0 read1
136574472 + 0 read2
(...)
```

You can see all the QC-failed reads are filtered out, since `0xB00` includes `0x200`.

**Comment by priyanka-surana** [comment]
`samtools fastq` command updated with `-F 0x200` for both HiC and Illumina reads.
