### ISSUE TITLE
Bwa-mem2 mem parallelisation

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/readmapping#35]
### Description of feature

For illumina and hic, I want to break the input fastq files, align them against the genome. The split files need to be aligned with the same `@RG` tag. 

1. Split fastq using `split`
2. Make sure all split files have the same `@RG` tag
3. Run bwa-mem2 mem on them individually
4. Sort them with samtools individually
5. Merge all split alignments from the same individual with `-c` tag
6. Merge at the specimen level. 
7. Run through the rest of the `markdup_stats` subworkflow

Maybe possible to combine steps (5) and (6).

**Comment by priyanka-surana** [comment]
@muffato Based on the latest discussion with Shane, are we still focusing on splitting by FASTQ. He recommended we split by BAM/CRAM to avoid excess I/O.

**Comment by muffato** [comment]
If you can avoid converting to fastq, please do so. It's a valid disk optimisation even without splitting the input file
