### ISSUE TITLE
Name the output files with the assembly name

### ISSUE THREAD

**Issue by muffato** [sanger-tol/readmapping#36]
### Description of feature

All output files are currently named `assembly.*`. As Kerstin suggested, it'd be nicer to use the actual assembly name instead of the fixed string `assembly`, so that all files can be recognised even outside of the directory structure.

**Comment by priyanka-surana** [comment]
Are we converting to `assembly.hic.ilParAegt2.cram` to `ilParAegt2.hic.cram` or `GCA_905163445.1.hic.ilParAegt2.cram`?

**Comment by muffato** [comment]
`GCA_905163445.1` as `ilParAegt2.1` can be reused between assemblies and is not unique

**Comment by priyanka-surana** [comment]
It is done. I forgot to close it.
