### ISSUE TITLE
Pipeline logo size too big to make email hard to read

### ISSUE THREAD

**Issue by gq1** [sanger-tol/readmapping#43]
### Description of feature

Can we change the image size or update the email template?

**Comment by priyanka-surana** [comment]
I think you will need to modify this file.
https://github.com/sanger-tol/readmapping/blob/lsf-full-test/lib/NfcoreTemplate.groovy

**Comment by gq1** [comment]
Not modify this file but the following line call the email template:
https://github.com/sanger-tol/readmapping/blob/0e694aa0a8cd373d11a908a26cf5e38042607a6d/lib/NfcoreTemplate.groovy#L114

Here is the line in the email template to define the image, i think:
https://github.com/sanger-tol/readmapping/blob/0e694aa0a8cd373d11a908a26cf5e38042607a6d/assets/email_template.html#L22

**Comment by priyanka-surana** [comment]
I think there is also an option to get plain text emails instead of html.

**Comment by gq1** [comment]
Yes, it is. But by default, it is html.

**Comment by gq1** [comment]
https://github.com/sanger-tol/readmapping/pull/45
