### ISSUE TITLE
tracedir not being defined properly when outdir defined

### ISSUE THREAD

**Issue by gq1** [sanger-tol/readmapping#44]
### Description of the bug

https://github.com/sanger-tol/readmapping/blob/0e694aa0a8cd373d11a908a26cf5e38042607a6d/nextflow.config#L31

`outdir`'s value is not being passed to `tracedir`, the pipeline use` '${params.outdir}/pipeline_info'` instead.

**Comment by priyanka-surana** [comment]
Are you saying the folder name is `${params.outdir}` instead of `results` for example?

**Comment by gq1** [comment]
Yes, only for trace files. There is a `results` folder but with other outputs.

**Comment by gq1** [comment]
Just realised this problem is NF-tower web UI specific. 

When you load your pipeline into the UI, tower pre-populate each field with their default vaules defined in the config file.
For `tracedir`, it will be `${params.outdir}/pipeline_info`

When you click Launch button, the tower read each field back and run.
At this time `--tracedir `${params.outdir}/pipeline_info`` being passed to nextflow run.

To avoid this, we may not use variable for other field's value in the config files or set a new value in the UI but this field is hidden.
