### ISSUE TITLE
Add multiple output options

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/readmapping#64]
### Description of feature

To close this issue:
1. Add a new parameter `--outfmt` which takes values `bam` or `cram`, and a new parameter `--compression` which takes values `none` or `crumble`. User can pass multiple options separated by a `,`.
2. In the main workflow or the `input_check` sub-workflow, parse and validate the parameter values, and pass these to the `convert_stats` sub-workflow.
3. Configure the `convert_stats` sub-workflow to only run `CRUMBLE` if `--compression crumble` is passed, and to only run `SAMTOOLS_VIEW` if `--outfmt cram` is passed.
4. Run tests to make sure `--outfmt` works as expected.
5. Update the documentation.

**Comment by muffato** [comment]
crumble works on BAM files too, so the choices are 1) BAM vs CRAM, 2) original scores vs compressed scores (crumble)
