### ISSUE TITLE
Try minimap2 splice

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/readmapping#66]
### Description of feature

The BlastN step in PacBio read filtering is slow. A suggestion from Yumi was that we could try [`minimap2 splice`](https://github.com/lh3/minimap2/blob/master/README.md#map-long-splice). 

Compare run time between BlastN vs Minimap2 Splice and select the more efficient option.

**Comment by tkchafin** [comment]
Closing as we have determined minimap splice to not work as an alternative
