### ISSUE TITLE
Remove repeat masking from genome files

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/readmapping#7]
### Description of feature

Remove soft repeat masking from genome files as part of the `prepare genome` subworkflow before it moves to alignment. 

Possible options: Need to write a module for either.
1. `awk`
```
awk 'BEGIN{FS=" "}{if(!/>/){print toupper($0)}else{print $0}}' in.fna > out.fna
```
2. `BBtools reformat.sh`
```
reformat.sh in=file.fasta out=fixed.fasta trd tuc -Xmx1g
```

**Comment by muffato** [comment]
1. I think it's not worth parallelising
2. https://anaconda.org/conda-forge/gawk 5.1.0, quay.io/biocontainers/gawk:5.1.0, will have awk

**Comment by priyanka-surana** [comment]
@muffato 

Unmasking the genome has changed the `index` output structure a bit:
```
results/assembly/indices/
├── bwamem2
│   ├── GCA_927399515.1_OV656674.1.unmasked.fasta.0123
│   ├── GCA_927399515.1_OV656674.1.unmasked.fasta.amb
│   ├── GCA_927399515.1_OV656674.1.unmasked.fasta.ann
│   ├── GCA_927399515.1_OV656674.1.unmasked.fasta.bwt.2bit.64
│   └── GCA_927399515.1_OV656674.1.unmasked.fasta.pac
└── GCA_927399515.1_OV656674.1.unmasked.mmi
```

Is this okay? Do you want to save the unmasked genome as well?

**Comment by muffato** [comment]
By the way, I don't remember if we discussed that, but _all_ aligners should use the unmasked genome. One purpose of the alignments is to be able to look at the read coverage across the _entire_ genome.

**Comment by priyanka-surana** [comment]
Yes we updated that. Now it uses the unmasked genome and its associated index for alignments.
