### ISSUE TITLE
cram input necessary?

### ISSUE THREAD

**Issue by gbdias** [sanger-tol/readmapping#88]
I was wondering if the cram input requirement for HiC data alignment makes sense since the first step of the pipeline is to convert back to fastq. Would it be ok to also accept fastq as input and skip this step?
https://github.com/sanger-tol/readmapping/blob/a27e9ce841d230f3c1ca5086019a134a116bee18/subworkflows/local/align_short.nf#L21

**Comment by muffato** [comment]
Hi @gbdias . You're absolutely right

**Comment by yumisims** [comment]
@gbdias We use CRAM files as input for several reasons:
(1) to save storage, which is very obvious.
(2) CRAM files can be segmented into 10k containers per batch for streaming in BWA-MEM2/Minimap2 using cram_filter, allowing us to parallelize the process. This significantly enhances the alignment performance.

**Comment by gbdias** [comment]
hi @yumisims thanks for the info. I can appreciate the advantage of streaming CRAM to bwa mem. I was just confused because the current code doesn't seem to use CRAM like that, in which case taking fastq directly would be faster.

**Comment by muffato** [comment]
You're right @gbdias, the pipeline here doesn't implement the parallel aligner @yumisims is talking about, which requires CRAM, and is currently implemented in https://github.com/sanger-tol/treeval
